export const DISTRICT_KEYS = [
    'adilabad',
    'bhadradri_kothagudem',
    'hyderabad',
    'jagtial',
    'jangaon',
    'jayashankar_bhupalpally',
    'jogulamba_gadwal',
    'kamareddy',
    'karimnagar',
    'khammam',
    'komaram_bheem_asifabad',
    'mahabubabad',
    'mahabubnagar',
    'mancherial',
    'medak',
    'medchal_malkajgiri',
    'mulugu',
    'nagarkurnool',
    'nalgonda',
    'narayanpet',
    'nirmal',
    'nizamabad',
    'peddapalli',
    'rajanna_sircilla',
    'ranga_reddy',
    'sangareddy',
    'siddipet',
    'suryapet',
    'vikarabad',
    'wanaparthy',
    'warangal_rural',
    'warangal_urban',
    'yadadri_bhuvanagiri',
] as const

export type DistrictKey = (typeof DISTRICT_KEYS)[number]
