DROP TABLE IF EXISTS preparations CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS scan_results CASCADE;
DROP TABLE IF EXISTS disease_remedies CASCADE;
DROP TABLE IF EXISTS crop_variety_diseases CASCADE;
DROP TABLE IF EXISTS remedies CASCADE;
DROP TABLE IF EXISTS diseases CASCADE;
DROP TABLE IF EXISTS crop_varieties CASCADE;
DROP TABLE IF EXISTS crops CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;

-- Drop helper function
DROP FUNCTION IF EXISTS is_admin();
